### ISSUE TITLE
[Keccak] `decompose` - tests with corner cases would be nice to have

### ISSUE THREAD

**Issue by dannywillems** [o1-labs/proof-systems#1324]
I will sound annoying :): but tests with corner cases would have been nice to have, just for the reviewers to be convinced it is fine at a first sight.

_Originally posted by @dannywillems in https://github.com/o1-labs/proof-systems/pull/1268#discussion_r1381742752_

**Comment by querolita** [comment]
Let me know if this issue still applies after the new tests added
