### ISSUE TITLE
LGTM. Does follow the RFC. Only shifts -> reset.

### ISSUE THREAD

**Issue by dannywillems** [o1-labs/proof-systems#1325]
LGTM. Does follow the RFC. Only shifts -> reset.

_Originally posted by @dannywillems in https://github.com/o1-labs/proof-systems/pull/1248#pullrequestreview-1712763654_

**Comment by querolita** [comment]
Fixed the RFC in commit [e5aacfe](https://github.com/o1-labs/rfcs/pull/27/commits/e5aacfe7e0131ba9c618fd26c60ddf3148f95d14) so that implementation and RFC follow the same notation.
