### ISSUE TITLE
Add a test checking the domain size when building a circuit with gates using same table.

### ISSUE THREAD

**Issue by dannywillems** [o1-labs/proof-systems#1335]
Approving, but would have been nice to have a test, even it looks fine regarding the code. Opening a follow-up issue for a 10 min task.

_Originally posted by @dannywillems in https://github.com/o1-labs/proof-systems/pull/1334#pullrequestreview-1734526395_
           
 Before this PR, it was duplicating the domain if two gates were using the same table.

**Comment by mrmr1993** [comment]
More specifically, if distinct lookup patterns used the same table, the table would be added once fr each, which in turn could increase the domain size.

**Comment by duguorong009** [comment]
@dannywillems 
I picked the issue, assuming that it is for external contributor. 
Can you check the PR?
