### ISSUE TITLE
Add mdbook-linkcheck

### ISSUE THREAD

**Issue by dannywillems** [o1-labs/proof-systems#1359]
Could you please change it to `[Extended Lookup Tables](../kimchi/extended-lookup-tables.md)`?

Also do we have some mechanism to check broken references? Like https://docs.rs/mdbook-linkcheck/latest/mdbook_linkcheck/

_Originally posted by @volhovm in https://github.com/o1-labs/proof-systems/pull/1346#discussion_r1410394956_

**Comment by volhovm** [comment]
This PR introduces the desired feature: https://github.com/Michael-F-Bryan/mdbook-linkcheck/pull/81.

But even if it's merged we'd need to wait for mdbook-linkcheck to get released if I understand correctly? (or can we use a dev version?)

**Comment by dannywillems** [comment]
> This PR introduces the desired feature: [Michael-F-Bryan/mdbook-linkcheck#81](https://github.com/Michael-F-Bryan/mdbook-linkcheck/pull/81).
> 
> But even if it's merged we'd need to wait for mdbook-linkcheck to get released if I understand correctly? (or can we use a dev version?)

Yes, let's wait for a release.
Is the project still maintained?

**Comment by volhovm** [comment]
It seems maintained. I'll ping `Micheal-F-Bryan` again in a week. It's all done so I'm a bit annoyed it can't be merged only because I'm not getting any replies...
