### ISSUE TITLE
sign extended: Note also the value 0 has two representations. Would be good to import the tests.

### ISSUE THREAD

**Issue by dannywillems** [o1-labs/proof-systems#1400]
Note also the value 0 has two representations. Would be good to import the tests.

_Originally posted by @dannywillems in https://github.com/o1-labs/proof-systems/issues/1396#issuecomment-1841396922_

**Comment by mrmr1993** [comment]
No it doesn't: https://github.com/o1-labs/proof-systems/issues/1436#issuecomment-1843234247
