### ISSUE TITLE
Check that addresses are aligned

### ISSUE THREAD

**Issue by dannywillems** [o1-labs/proof-systems#1406]
Note: addresses must be aligned
![image](https://github.com/o1-labs/proof-systems/assets/6018454/a778c5a3-ff05-420f-a70d-d0acafef6c12)

_Originally posted by @dannywillems in https://github.com/o1-labs/proof-systems/issues/1395#issuecomment-1841525703_

**Comment by mrmr1993** [comment]
https://github.com/o1-labs/proof-systems/issues/1456
