### ISSUE TITLE
Handle division by zero

### ISSUE THREAD

**Issue by dannywillems** [o1-labs/proof-systems#1447]
> Crazy no exception is raised...

Cannon doesn't guard these, so doing a division by 0 will crash cannon. As such, I was just going to make it unprovable :)

_Originally posted by @mrmr1993 in https://github.com/o1-labs/proof-systems/issues/1427#issuecomment-1843216408_

**Comment by mrmr1993** [comment]
I don't think that having these individual issues is a good or useful thing, especially with the current title. Please close all of them and create a 'handle MIPS instruction exceptions' master issue to de-clutter the issues.

**Comment by mrmr1993** [comment]
https://github.com/o1-labs/proof-systems/issues/1447
