### ISSUE TITLE
Reducing the size of the dlog based reference string

### ISSUE THREAD

**Issue by imeckler** [o1-labs/proof-systems#15]
For the dlog-based argument, we need random group elements $g_i$ for $i < N$ where $N$ is the max-degree of a polynomial sent in the underlying IOP.

Currently that degree is about 1,200,000. It can be reduced to about 600,000 by indexing `row*col` and then say to 150,000 by chopping the high degree commitment up into 4. We could also chop it up into more pieces, although we would also need to start chopping up other ones as well since the size of H is about 100,000.

One group element is 2x48 bytes. 1 MB is about 10,000 group elements. So we would need about 15 MB to store the whole 150,000 group element URS. This is somewhat problematic for the browser clients. I believe we should shoot for a URS size of at most 5 MB, since that is the size of local storage on most mobile browsers.

One way out is to regenerate the group elements on the client, using a hash-to-curve. Let hashToField : N \to F be the function that blake2b hashes its input and then interprets it as a field element.

Following [BW19](https://eprint.iacr.org/2019/403.pdf), there is an algorithm \phi : F \to G. We get a hash-to-curve as the  composite of \phi with hashToField.

First \phi computes three potential x coordinates x_0, x_1, x_2, and then picks the first one for which f(x_i) is a square. The curve point \phi(t) is then \sqrt{f(x_i)}.

We can cheaply compute all of the x coordinates, so there is no need to send these to the client. Getting from the x coordinate to the curve point is expensive because it requires

1. checking which f(x_i) is a square
2. computing a square root.

## Eliminating the squareness checks

Checking which f(x_i) is a square is somewhat expensive. It requires computing a Legendre symbol. Happily, there is a way to do some precomputation to avoid having to compute any Legendre symbols.

Namely, we can provide the client with an advice string of 2 bits per group element giving the index in {0, 1, 2} corresponding to the correct choice of x_i. For 150,000 group elements this works out about 36 kilobytes.

So, for each i, we compute a_i := x_{index[i]}(blake2b(i)) and then g_i := (a_i, sqrt{a_i}).

Computing the x coordinates involves a blake2b invocation, some multiplications, and some inversions. The blake2b and the multiplications are cheap, and we can use batch inversion over all the group elements to amortize the cost of the inversion.

## Eliminating the square root computation

I don't believe there is any way to eliminate this. However, we can eliminate some of the computation by sending some of the y coordinates to the client.

We don't need to send the client any of the x coordinates since they should be fairly cheap to recompute. This means we can just send the y coordinates and the index advice, which works out to about 7.5 MB.

7.5 MB is still a bit too much, so we can just send as many of the y coordinates that fit in our 5 MB space and recompute the rest. This reduces the number of square roots we need to compute from roughly 150,000 to 50,000.

**Comment by ValarDragon** [comment]
This was pointed out to me by Justin Drake, but its possible to compress multiple points with better computational overhead thats significantly better than one sqrt per element. You have one extra field element for the compression, but in exchange you get much better decompression performance.

https://link.springer.com/article/10.1007%2Fs10623-016-0251-2

Page 10 has the following table for compressing points:
![Screenshot from 2019-12-15 01-12-34](https://user-images.githubusercontent.com/6440154/72290384-a5f79980-3612-11ea-9d6c-e339fffe24e1.png)

(S means squaring)

**Comment by imeckler** [comment]
@ValarDragon Investigating this seems to require O(n^2) computation for computing and applying the van der monde matrix as far as I can tell. (In the paper they explain that they treat n as a constant.)

**Comment by ValarDragon** [comment]
That make sense. Couldn't you set n to be the size that has the best ratio between Ordinary and Multiple? For the given example in the table, it seems like `n=5` should give a 3 to 5x speed improvement
