### ISSUE TITLE
Bring expression framework to Large MSMs, implement a simple test circuit

### ISSUE THREAD

**Issue by volhovm** [o1-labs/proof-systems#1790]
Create an MSMEnv similar to how it's done in zkVM, make sure commitments are created and evaluated properly. Make sure it works with lookups.

**Comment by dannywillems** [comment]
Depends on https://github.com/o1-labs/proof-systems/pull/1807 for lookups.

**Comment by dannywillems** [comment]
Based on our Friday meeting, @volhovm wanted to take this task, after we went through the code together, and I explained how it should be added.
