### ISSUE TITLE
Implement FFA addition

### ISSUE THREAD

**Issue by volhovm** [o1-labs/proof-systems#1791]
Implementing a simple bigint-based addition for the foreign field.

Write a test.

**Comment by dannywillems** [comment]
Depends on https://github.com/o1-labs/proof-systems/pull/1807 for the rangecheck16

**Comment by volhovm** [comment]
@dannywillems nonono, the final PR with the actual code is this one: https://github.com/o1-labs/proof-systems/pull/1934, and it still has https://github.com/o1-labs/proof-systems/pull/1932 as prerequisite, so not done yet...

**Comment by dannywillems** [comment]
I did not close it. It has been done automatically.
