### ISSUE TITLE
Scale up sub-MSM to the circuit limits 

### ISSUE THREAD

**Issue by volhovm** [o1-labs/proof-systems#1795]
With the previous estimates and $N=2^{13}$ we can do $l = 254/k \approx 17$ independent proofs, each for a run of the sub-MSM algorithm.

But the circuit has a lot of extra space, since we have quarter of the rows empty.

Instead we can try to fit 3 additions per row, in which case we'll be able to run 4 iterations of the sub-MSM algorithm per circuit, reducing the number of proofs to $l/4$. This increases the proof size, of course, but is more efficient.

**Comment by joseandro** [comment]
Not valid anymore
