### ISSUE TITLE
MSM: Circuit unfolding IPA challenges

### ISSUE THREAD

**Issue by volhovm** [o1-labs/proof-systems#1834]
We need to create a separate circuit for the MSM project that will consume IPA challenges (15-16), and produce (2^15 or 2^16) MSM coefficients.
>1 proof computing the coefficients for the 2^15 Pallas scalars from the bulletproof challenges
> - the bulletproof challenges will be looked-up from a column (or 2, we may need to account for overflow)
> - the results will appear as a column (or 2), no need to use lookups because they'll appear in order in the trace

**Comment by dannywillems** [comment]
I keep a note for a potential optimisation for a second version.

The polynomial $h(X)$ is computed as follow: given a family $\xi_{i}$,

$$h(X) = \prod_{i = 0}^{M} (1 + \xi_{i} X^{2^{i}})$$

We observe that, unfolded, the polynomial will have only monomials with multiple of $2$.

$$h(X) = \prod_{i = 0}^{N} \zeta_{i} X^{2 i}$$

When we unfold the polynomial, and try to find a formula, we have a certain structure on the coefficients $\zeta_{i}$. We observe that the coefficients of $\zeta_{i}$ will be the product of $\xi_{j}$ where we decompose $i$ in base 2, and we take the corresponding $\xi_{j}$.
For instance, $\zeta_{2} = \xi_{1}$, $\zeta_{5} = \xi_{1} \xi_{2}$.

While computing the coefficients, we can cache/accumulate the values $\zeta_{i} and only multiply with the coerresponding $\xi_{i}$.

While we compute the FF multiplication, as we already process in limbs of 15 bits, there might be a way to merge the two circuits, and optimise.
