### ISSUE TITLE
[kimchi] absorbing all the values!

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#221]
in [plonk_sponge.rs](https://github.com/o1-labs/proof-systems/blob/master/dlog/kimchi/src/plonk_sponge.rs#L38), it's too easy to forget to absorb some of the evaluation values. So here we should discuss:

- is this really needed? It's not clear to me, as we're already absorbing the digest of the other sponge and it authenticates these values already IIUC.
- if it is needed, can be make it less error-prone? Perhaps use some generated-code (via macros).

**Comment by mimoo** [comment]
I think there's actually an quick 'n easy way to address this issue atm without resorting to macros! @mrmr1993  used a technique earlier which really inspired me and I implemented it here as part of a larger PR that might never see the light of day: https://github.com/o1-labs/proof-systems/pull/680/files#diff-7d26d412f0cf053bc5fbbc590ab9c3760a3f2bfd0ef7ff640781d7ba127bc905R201

the technique is to deconstruct whatever it is we really want to use all of, and if we don't use one of the things the linter will yell at us (and CI won't let us merge the PR):

```rust
impl<F: Field> ProofEvaluations<F> {
    /// Returns an iterator over all evaluations contained in [Self].
    pub fn iter(&self) -> impl Iterator<Item = F> {
        // important: we use a deconstruction pattern so that the compiler can tell us if we forget one of the evaluations
        let ProofEvaluations {
            w,
            z,
            s,
            lookup,
            generic_selector,
            poseidon_selector,
        } = self.clone();

        let mut values: Vec<F> = chain![
            std::iter::once(z),
            std::iter::once(generic_selector),
            std::iter::once(poseidon_selector),
            w,
            s,
        ]
        .collect();

        // important: at this point we assume that Self is well-formed and contains a lookup
        if let Some(lookup_evals) = lookup {
            // important: we use a deconstruction pattern so that the compiler can tell us if we forget one of the evaluations
            let LookupEvaluations {
                sorted,
                aggreg,
                table,
                runtime,
            } = lookup_evals;

            values.extend(chain![
                std::iter::once(aggreg),
                std::iter::once(table),
                sorted,
                runtime,
            ]);
        }

        values.into_iter()
    }
}

impl<F> AbsorbableScalarField<F> for [&ProofEvaluations<F>; 2]
where
    F: Field,
{
    fn absorb(&self, sponge: &mut impl FrSponge<F>) {
        let [zeta_evals, zeta_omega_evals] = &self;

        // we interleave points from each evaluations,
        // it makes it easier to absorb them in the verifier circuit
        let points: Vec<F> = zeta_evals
            .iter()
            .interleave(zeta_omega_evals.iter())
            .collect();

        sponge.absorb_multiple(&points);
  }
}

/// Implement this trait on a type to make it "absorbable" by a scalar sponge.
/// All types that the prover sends to the verifier in the protocol should implement this trait.
pub trait AbsorbableScalarField<F>
where
    F: Field,
{
    /// Takes a sponge and absorbs the field element of the struct into it.
    fn absorb(&self, sponge: &mut impl FrSponge<F>);
}
```

(I just pasted all the relevant code that could be pulled out and applied in a separate PR)

**Comment by mimoo** [comment]
perhaps @duguorong009 might be interested?

**Comment by duguorong009** [comment]
@mimoo 
Thanks for indicating me! 👼 
In fact, I am really interested in ZKP stuff & recently digging into.(Several books, practices like Halo2 tutorial)
Let me try to take care of the issue.
(One question, can you let me know the communication channel like Discord or Telegram group? 
I would like to join and ask you the questions I have)

**Comment by mimoo** [comment]
btw it's this point in the protocol: the prover sends a bunch of evaluations to the verifier, and so in the non-interactive version it is akin to absorbing with the hash function (poseidon) these points found in the proof (on both sides):

<img width="650" alt="Screen Shot 2022-09-14 at 5 29 22 PM" src="https://user-images.githubusercontent.com/1316043/190285948-b1dffab5-10af-4a9a-9342-9101d412f554.png">

taken from:

https://o1-labs.github.io/proof-systems/specs/kimchi.html#proof-construction--verification

**Comment by duguorong009** [comment]
> btw it's this point in the protocol: the prover sends a bunch of evaluations to the verifier, and so in the non-interactive version it is akin to absorbing with the hash function (poseidon) these points found in the proof (on both sides):
> 
> <img alt="Screen Shot 2022-09-14 at 5 29 22 PM" width="650" src="https://user-images.githubusercontent.com/1316043/190285948-b1dffab5-10af-4a9a-9342-9101d412f554.png">
> 
> taken from:
> 
> https://o1-labs.github.io/proof-systems/specs/kimchi.html#proof-construction--verification

Thanks for the detail! @mimoo 👍 
Yes, I will try to understand the flow & take care of issue as much as possible.

**Comment by duguorong009** [comment]
@mimoo 
I checked the issue detail & the PR you mentioned(https://github.com/o1-labs/proof-systems/pull/680).
I think the PR #680 already has everything that this issue needs to solve.
The question is, why do you put off the merge of PR #680? 
It can bring about much improvement, including this issue solution.

**Comment by mimoo** [comment]
Ah, we decided not to go for it because we want to be able to support chunked evaluations down the line. Thanks for pushing me to write an issue on that :D https://github.com/o1-labs/proof-systems/issues/759

If you're interested feel free to look at it as well! I think both are interesting (although this one should be much more straight forward)

**Comment by duguorong009** [comment]
Thanks so much! @mimoo 
Yes, I will try to take care of these 2 issues myself, and create PRs. 😄

**Comment by duguorong009** [comment]
@mimoo 
I think we could close this issue because of the PR #875.
What do you think?

**Comment by mimoo** [comment]
I still think we should also use the iter trick for the arrays (w, coefficients, and s) so we're not doing an off by one or something :o

**Comment by duguorong009** [comment]
I see, will take a look again.
