### ISSUE TITLE
Add license info for all crates

### ISSUE THREAD

**Issue by willemolding** [o1-labs/proof-systems#222]
We are using an number of these crates in [mina-rs](https://github.com/ChainSafe/mina-rs). It is our enforced CI policy to not depend on any crates without a license.

It would be great if the correct license could be added to the Cargo.toml for each crate.

Thanks!

**Comment by mimoo** [comment]
Any advice on what license we should use? Cc @imeckler

**Comment by creativcoder** [comment]
Probably the same used in [mina](https://github.com/MinaProtocol/mina#license)? i.e., Apache 2.0
