### ISSUE TITLE
Reduce round complexity from 4 to 3

### ISSUE THREAD

**Issue by ValarDragon** [o1-labs/proof-systems#24]
I'm not sure how much performance for the prover / verifier that needs to be squeezed, but you can reduce one round from Marlin's holographic lincheck. This is done by changing to index the transpose of the matrix, and using Claim 6.7 of the Fractal paper: https://eprint.iacr.org/2019/1076.pdf page 28.

This would reduce one round, and one degree H commitment from the protocol. If this would be useful, I can work through how exactly this changes the Marlin AHP.

**Comment by Pratyush** [comment]
(We have an implementation of this in our private repo which we’d like to put online in a few days, along with an update to the paper)

**Comment by Pratyush** [comment]
"Few days" turned out be more like "few months", but the PR implementing this is up now at https://github.com/scipr-lab/marlin/pull/18

The paper should be updated some time tomorrow
