### ISSUE TITLE
Add Selectors

### ISSUE THREAD

**Issue by marcbeunardeau88** [o1-labs/proof-systems#2543]
The current desgin of the o1vm is one circuit per MIPS instructions.
We want to change that and get one big circuit which does all the instruction depending on which selector is activated.

We need to add ‘selectors’ for (see [kimchi](https://github.com/o1-labs/proof-systems/blob/997847b767ecc0e9a48d1a9ae521d59e8bc7671c/kimchi/src/prover.rs#L654) and/or [the original zkVM prototype](https://github.com/o1-labs/mips-demo), the plonk paper for the concept), and multiplex the instructions using those. The [original zkVM](https://github.com/o1-labs/mips-demo/blob/70c93219a826028abe519f20e6698c07d0cafd24/kimchi/src/mips/witness.rs#L576) is probably the best guide for this, this is how it originally worked.

**Comment by Fizzixnerd** [comment]
CC @dannywillems @marcbeunardeau88 

I was wondering: do we want one giant selector `q_MIPS` which serves as essentially the opcode for MIPS, or several smaller selectors `q_leftshift` and friends that are in the range `{0, 1}`.

Or, is the selector something more clever than what I'm initially thinking of?  For example, it might be possible to construct `Z` such that

```Z(g^i, x) = MIPS_instruction(i)(x)```

By using the same trick in Section 5 of PlonK.

**Comment by Fizzixnerd** [comment]
Closed in #2671
