### ISSUE TITLE
gates should implement an interface

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#271]
* every gate should implement the same clear interface
* every gate should also return a vector of constraints, and we should have some logic that always combine these constraints (so we can't forget to combine them)

cc @jspada @querolita

**Comment by mimoo** [comment]
Currently the prover code looks like a lot of repeat of this:

```rust
            let emulscalar8 =
                endomul_scalar::constraint(range::ENDOMUL_SCALAR.start).evaluations(&env);
            t8 += &emulscalar8;

            if cfg!(test) {
                let (_, res) = emulscalar8
                    .clone()
                    .interpolate()
                    .divide_by_vanishing_poly(index.cs.domain.d1)
                    .unwrap();
                assert!(res.is_zero());
            }
```

it'd be really awesome if we can just have something like that:

```rust
for gate in gates {
   let gate_eval = gate.evaluations(&env);
   test_gate!(gate_eval);
   evaluation += gate_eval;
}
```

**Comment by querolita** [comment]
Actually I thought we were thinking of some trait for gates to have a common set of functions such as `create`, `verify`, `gadget` or similar.

**Comment by mimoo** [comment]
I have a PR out to add an interface for gates: https://github.com/o1-labs/proof-systems/pull/295

I don't think we can create an interface for create, as different gates take different inputs. Although... saying that I think the following interface would work:

```rust
pub trait Gate {
   type Inputs;
   fn create(input: Inputs, ...) -> ...
}
```
