### ISSUE TITLE
Don't use `usize` for anything except memory accesses

### ISSUE THREAD

**Issue by mrmr1993** [o1-labs/proof-systems#346]
We should never use `usize` for anything except memory accesses (ie. array indexing and lengths), and we should always prefer fixed-size integers unless we are directly managing memory.

This was the root cause of the poseidon breakage in SnarkyJS+WASM (#345): we were using encoding integers as `usize` and then treating them as if `usize = u64`. We will continue to create these kinds of issues until we fix this.

**Comment by mimoo** [comment]
I've noticed a lot of `usize` in the codebase that don't really make sense, even to interpret rows of a circuit it doesn't make sense to use a `usize` imo.

**Comment by mimoo** [comment]
BTW, the problematic conversions:

1. `usize as u32`, you can have a truncation.
2. `u64 as u32`, you can have a truncation.
3. `u64 as usize`, same as the previous one when running on a machine where `usize = u32`.

I think the first two are unlikely to be seen in our codebase, but the third one is definitely happening in a number of places. The third one is only an issue when we're using values that are larger than 32 bits, which might be unlikely anyway. Still, we might want to use `usize::try_from(u64).expect("32-bit conversion issue")` in places where we do this. (Or create a shorter helper to do this.)

**Comment by mrmr1993** [comment]
We probably want `u32` nearly everywhere, `usize` for memory, and `u64` pretty much just for the encodings that use it (e.g. limbs of `BigInt256`/`Fp`/`Fq`).

There's a slight wrinkle in dealing with OCaml, since the int type uses `usize` (where the top bit is never set); however, porting this code to js_of_ocaml+WASM will also cause a problem, because JS can only faithfully represent a u32 in the number type. In these cases we should probably `TryInto::try_into::<u32>(ocaml_int).map_err(|_| { Error(ocaml::failwith "function_name: Integer argument uses more than 32 bits")})?`. A macro for this might be nice.

**Comment by mimoo** [comment]
Yeah I think that's a good idea, switching everything to `u32`

> There's a slight wrinkle in dealing with OCaml, since the int type uses usize (where the top bit is never set);

That's really annoying that ocaml-rs let's you make that mistake. I brought that up here https://github.com/zshipko/ocaml-rs/issues/71 but I don't think it's sensible that we have to remember these things when writing bindings

**Comment by mrmr1993** [comment]
> I brought that up here https://github.com/zshipko/ocaml-rs/issues/71 but I don't think it's sensible that we have to remember these things when writing bindings

It's not a bug in ocaml-rs: using the native machine word size exactly matches the OCaml compiler's behaviour, and allows you to write correct code across architectures. The real issue is that we were not writing that correct code.

**Comment by mimoo** [comment]
ah yeah that's when we use `ocaml::Int` directly. Are you saying that using `usize` with values that are dangerously close to `usize::MAX` in something that will be converted to OCaml is dangerous?

**Comment by mrmr1993** [comment]
> Are you saying that using `usize` with values that are dangerously close to `usize::MAX` in something that will be converted to OCaml is dangerous?

IIRC the top bit will be dropped: `x: ocaml::Int` gets converted by the OCaml compiler by `(x << 1) | 1`. So technically yea, it could be considered dangerous. However, `js_of_ocaml` uses `2^32 - 1` as the max instead of `machine_word_max/2 + 1`, so we should be safe with any value `0 <= x < 2^32` in practice, at least until we add support for 32-bit architectures.
