### ISSUE TITLE
Move recursion in {prover,verifier} behind an Option

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#357]
It'd be nice if someone could easily use kimchi for non-recursive proofs. Would be good to move this behind an option, and have a "RecursionStuff" type or something.

More detail:

The relevant code is here in the prover: https://github.com/o1-labs/proof-systems/blob/master/kimchi/src/prover.rs#L94

```rust
    pub fn create<EFqSponge: Clone + FqSponge<Fq<G>, G, Fr<G>>, EFrSponge: FrSponge<Fr<G>>>(
        group_map: &G::Map,
        mut witness: [Vec<Fr<G>>; COLUMNS],
        index: &Index<G>,
        prev_challenges: Vec<(Vec<Fr<G>>, PolyComm<G>)>,
    ) -> Result<Self> {
```

the `prev_challenges` should be an `Option`. This should impact:

* the result: `ProverProof` has a `prev_challenges` field that should be behind an `Option<SomeType>` where `SomeType` indicates that this is about recursion
* the `create` function will have to skip the recursion stuff if it's `None`, basically ignore the prev_challenges
* and the [verifier](https://github.com/o1-labs/proof-systems/blob/master/kimchi/src/verifier.rs#L241) will have to do the same if it's set to `None`

**Comment by mimoo** [comment]
also, if someone wants to take over, I drafted something here: https://github.com/o1-labs/proof-systems/pull/364/files

**Comment by iammadab** [comment]
Taking this up.

**Comment by mrmr1993** [comment]
> It'd be nice if someone could easily use kimchi for non-recursive proofs.

This should already be possible: giving an empty `prev_challenges` vector achieves exactly this.

> Would be good to move this behind an option, and have a "RecursionStuff" type or something.

I think the `prev_challenges` field name and the unnamed `(Vec<Fr<G>>, PolyComm<G>)` type make it less clear that these can be skipped in a non-recursive proof. From my perspective, this issue would be better as:
* add a named type for `(Vec<Fr<G>>, PolyComm<G>)` that indicates that it is about recursion
* rename the field and the function argument to make it clearer that it's about recursion
* rename `ProverProof::create` to `ProverProof::create_recursive` (/ some better name)
* create `ProverProof::create` that calls `ProverProof::create_recursive` with the argument set to the empty vector

**Comment by mimoo** [comment]
Agree, that would be a great way to do this!
