### ISSUE TITLE
move CommitmentCurve to own module

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#380]
the trait `CommitmentCurve` is in the poly-commitment crate, which doesn't seem like a relevant place to have it. It'd be good to move it, as well as the relevant code (implementation here https://github.com/o1-labs/proof-systems/blob/master/poly-commitment/src/commitment.rs#L399) to the [mina-curve crate](https://github.com/o1-labs/proof-systems/blob/master/curves/)

https://github.com/o1-labs/proof-systems/blob/master/poly-commitment/src/commitment.rs#L366

**Comment by mimoo** [comment]
it'd be good to document the trait as well, but this can be done in a separate PR

**Comment by mrmr1993** [comment]
I disagree about moving it into `mina-curves`, since nothing about it is specific to the particular choice of curves we use in mina. The implementations could be moved, but it seems like `poly-commitments` is the perfect place for `CommitmentCurve`.

**Comment by mimoo** [comment]
I was thinking that mina-curves could also host elliptic curve stuff. the util crate would be another solution, wdyt?

**Comment by mrmr1993** [comment]
I think it's fine where it is, and that we shouldn't mix the generic implementations with the specific curves that we use. Why do you want to move it?

**Comment by mimoo** [comment]
Trying to find refactoring opportunities in https://github.com/o1-labs/proof-systems/blob/master/poly-commitment/src/commitment.rs#L399 as it's a large file. I'd be fine if we move it to its own module under poly-commitment as well. Thanks for the insight

**Comment by mrmr1993** [comment]
The title of this issue should probably be `refactor/split up commitment.rs` then.
