### ISSUE TITLE
move ceil_log2 to utils

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#386]
move [ceil_log2](https://github.com/o1-labs/marlin/blob/4ea3d287e777b5c9d6dc49a82083631412ccbd63/poly-commitment/src/commitment.rs#L323) out of poly-commitment, and into the utils crate, as it's a more general function

**Comment by prateekm33** [comment]
I can pick this one up @mimoo

**Comment by prateekm33** [comment]
is there a specific file that we want to move it to in the `utils` crate or create a new file under that dir?

**Comment by mrmr1993** [comment]
None of the existing files seem like a good fit, but either in the toplevel `lib.rs` or a new file (e.g. `math.rs`) is sound good to me.
