### ISSUE TITLE
light documentation needed for groupmap crate

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#387]
the groupmap crate doesn't have a description in the [README](https://github.com/o1-labs/proof-systems/blob/master/README.md#organization), and it also doesn't have documentation in the crate. It'd be good to have some light documentation there at the very least.

**Comment by aaronsens** [comment]
going to work on this.

**Comment by mimoo** [comment]
Awesome thanks :)

**Comment by mimoo** [comment]
BTW @aaronsens hit me up if you want another task. I think it'd be nice to document more of the groupmap module (basically all `pub` structs and functions should be documented), if you're interested in digging more into what's happening there that'd be a good task. Otherwise I can find something else somewhere else on the codebase :o
