### ISSUE TITLE
[oracle] split permutation from sponge functions

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#389]
In the oracle crate (which probably should be renamed poseidon), we mix permutation stuff with sponge stuff in the same file. It'd be nice to have the permutation stuff in its own module. Specifically in https://github.com/o1-labs/marlin/blob/841dd0f52a04d8b4cb4783109e0dbe4b20eb93f9/oracle/src/poseidon.rs the following functions and types could be moved to a `permutation.rs`:

* apply_mds_matrix
* full_round
* half_rounds
* poseidon_block_cipher (probably should be renamed poseidon_permutation)

**Comment by mssabr01** [comment]
Hey I'll take this one!

**Comment by mssabr01** [comment]
I looked into changing the name of the crate from oracle to poseidon but it involves a lot of little changes in a lot of little files, along with some instances of stuff like poseidon::poseidon::ArithmeticSponge which looks kinda janky and I was having issues with rust not knowing which was the crate and which was the module that my meager rust chops weren't allowing me solve just yet. Maybe that is for another ticket?

**Comment by mimoo** [comment]
yeah probably not worth changing the name at this point
