### ISSUE TITLE
[oracle] split parameters for sponge vs permutation

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#390]
parameters for the permutation should be distinct from parameters for the sponge:

```rust
impl SpongeConstants for PlonkSpongeConstantsLegacy {
    const ROUNDS_FULL: usize = 63; // permutation
    const ROUNDS_PARTIAL: usize = 0; // permutation
    const HALF_ROUNDS_FULL: usize = 0; // permutation
    const SPONGE_CAPACITY: usize = 1; // sponge
    const SPONGE_WIDTH: usize = 3; // sponge
    const SPONGE_RATE: usize = 2; // sponge
    const SPONGE_BOX: u32 = 5; // permutation
    const FULL_MDS: bool = true; // permutation
    const INITIAL_ARK: bool = true; // permutation
}
```

perhaps split `SpongeConstants` into `PermutationParams` and `SpongeParams`?

EDIT: we're tabling this for now, we might revisit later, but now the PR is about changing to something like this:

```rust
trait SpongeConstants {
    const SPONGE_CAPACITY: usize = 1;
    const SPONGE_WIDTH: usize = 3;
    const SPONGE_RATE: usize = 2;

    const PERM_ROUNDS_FULL: usize = 63;
    const PERM_ROUNDS_PARTIAL: usize = 0;
    const PERM_HALF_ROUNDS_FULL: usize = 0;
    const PERM_SBOX: u32 = 5;
    const PERM_FULL_MDS: bool = true;
    const PERM_INITIAL_ARK: bool = true;
}
```

**Comment by frisitano** [comment]
PR up.  I wonder if we also want to change `PlonkSpongeConstantsLegacy` and `PlonkSpongeConstantsKimchi` to `PlonkSpongeParamsLegacy` and `PlonkSpongeParamsKimchi` for consistency.

**Comment by mrmr1993** [comment]
> parameters for the permutation should be distinct from parameters for the sponge:
> ...
> perhaps split `SpongeConstants` into `PermutationParams` and `SpongeParams`?

@mimoo I think this issue will serve to make the code worse rather than better, and would prefer to see this and the relevant PR closed without further action.

At a meta level: please stop opening issues like this, demanding eefact

**Comment by mimoo** [comment]
It's a bit messy to have the sponge and the permutation mixed. It doesn't make sense semantically, imo. This is how other codebases implement it (see [XKCP](https://github.com/XKCP/XKCP/tree/master/lib/low), the reference implementation of SHA-3 and others, or [Golang's implementation](https://cs.opensource.google/go/x/crypto/+/master:sha3/keccakf.go), for example. 

My argument is that we should be able to parameterized and reuse a permutation in different constructions (sponge, duplex, others), and mix and match (use sponge A with permutation B or sponge B with permutation A) which is what SHA-3 does for example.

Now I understand the "don't change it if it works". We can table it if you feel strongly about this. I'm still interested in PRs that can increase code readability and improve maintaining the codebase in the long run.

**Comment by mrmr1993** [comment]
> It's a bit messy to have the sponge and the permutation mixed. It doesn't make sense semantically, imo.

This is #389, right? I think that's entirely reasonable, and probably better for code health.

> My argument is that we should be able to parameterized and reuse a permutation in different constructions (sponge, duplex, others), and mix and match (use sponge A with permutation B or sponge B with permutation A) which is what SHA-3 does for example.

I see the logic, but we don't currently have a use for it, and in my experience it's hard to forward plan for things we're not doing without over- or mis-engineering.

Really my concern here is:
* we never use the permutation parameters in isolation from the sponge parameters;
* the code in this repo is mostly specialised to what we can/do support in the circuit, so it will be rare to introduce new parameters;
* separating the parameters will make the code more verbose to describe the same pairs that we already have;
* separating them will lead to more confusion/potential errors around which parameters to use in which combination -- double the number of combinations means double the chance for error!

It may be that a more natural division occurs as the changes for #389 progress, for example that the sponge parameters must include the permutation parameters as a sub-member/sub-trait/etc.. It may also be that we find this unnecessary. I would still strongly prefer not to move forward with this at this stage.

Also,

> Now I understand the "don't change it if it works".

for the record, I'm whole-heartedly in favour of any refactor that improves the code! I hope the above clarifies that I just don't believe that this is such a refactor.

**Comment by mimoo** [comment]
I do think it makes it harder for people familiar with sponges to understand or review the implementation, but I think that's a reasonable argument. Let's table it for now then. 

@frisitano sorry for that, let me know if you'd like to get a recommendation for another issue? Hopefully you still got something from that :D

**Comment by mrmr1993** [comment]
> It would still be useful to re-order and comment the struct though :)

@mimoo It would be nice to put the description in the names instead of in comments, e.g. `PERMUTATION_ROUNDS_FULL`. Also, I believe `SPONGE_BOX` is incorrect: `SBOX` normally stands for `SUBSTITUTION_BOX` IIRC. (Personally I prefer the look of `PERMUTATION_SBOX` to `PERMUTATION_SUBSTITUTION_BOX`, but either is fine by me.)

**Comment by mimoo** [comment]
yeah that'd be good. Also agree, `PERMUTATION_SBOX` is better

**Comment by frisitano** [comment]
@mimoo I will go ahead and re-order and rename trait consts.  Where can I read more about sponge params and permutations in context of poseidon?

**Comment by mimoo** [comment]
I would suggest the [poseidon paper](https://eprint.iacr.org/2019/458.pdf) :o
