### ISSUE TITLE
Move the 'joint lookup table' calculation into a helper function

### ISSUE THREAD

**Issue by mrmr1993** [o1-labs/proof-systems#395]
Currently we compute the 'joint lookup table' in the prover in 3 places:
* [as an iterator](https://github.com/o1-labs/proof-systems/blob/cc5ef9e0a4108e9ca623588d2187219cac090a01/kimchi/src/prover.rs#L257-L262) to pass to `lookup::sorted`
* [as a different iterator](https://github.com/o1-labs/proof-systems/blob/cc5ef9e0a4108e9ca623588d2187219cac090a01/kimchi/src/prover.rs#L319-L322) to pass to `lookup::aggregation`
* [as a vector](https://github.com/o1-labs/proof-systems/blob/cc5ef9e0a4108e9ca623588d2187219cac090a01/kimchi/src/prover.rs#L375-L383) to pass to `LookupEnvironment`

combining these into a single helper function would make it much simpler to maintain and modify the lookup code in the prover.

**Comment by mimoo** [comment]
https://github.com/o1-labs/proof-systems/pull/538 fixes that
