### ISSUE TITLE
Convert remaining panics into `Err` return values

### ISSUE THREAD

**Issue by mrmr1993** [o1-labs/proof-systems#396]
There are several `panic!` calls in [`ProverProof::create`](https://github.com/o1-labs/proof-systems/blob/cc5ef9e0a4108e9ca623588d2187219cac090a01/kimchi/src/prover.rs#L89) and [`Prover_index::create`](https://github.com/o1-labs/proof-systems/blob/cc5ef9e0a4108e9ca623588d2187219cac090a01/kimchi/src/prover_index.rs#L69). We would like these to be `Error` return values, so that we can support compilation targets with `panic_abort` (e.g. WASM via wasm_bindgen).

**Comment by CarloModicaPortfolio** [comment]
Hello! I will take care of this issue for the `Prover_index::create`

**Comment by ishangupta3** [comment]
I will check out the issue:  ProverProof::create side
