### ISSUE TITLE
Design of custom constraints for endo-scaling

### ISSUE THREAD

**Issue by imeckler** [o1-labs/proof-systems#41]
Recall that endomorphism-based scaling works on two bits at a time. 

Denote by b2i and b2i1 the bits at the (2i)-th position and the (2i+1)-nth position in the scalar. 
Denote the accumulated point as P.
Denote the point to be added as T (T will be added to P after some modifications though).

Q = (b2i1 ? (Endo * T.x) : T.x,  b2i ? T.y : -T.y)
R := P + Q
S := R + P

 The per two-bit constraints for variable-base scalar multiplication for groups with the special endomorphism are as follows:

<img width="217" alt="G1" src="https://user-images.githubusercontent.com/45769317/86288536-ec2fbd80-bb9e-11ea-96d4-8ee88a65e827.png">

Starting with Daira's approach here for basic variable-base scalar multiplication (i.e., without endomorphism): https://github.com/zcash/zcash/issues/4254#issuecomment-565761663, the variables can be arranged in 4 x 3 groups as follows. 

<img width="283" alt="G2" src="https://user-images.githubusercontent.com/45769317/86288555-f487f880-bb9e-11ea-8c25-a6fbee7f5867.png">

where, the PLONK custom gates are defined  as:

<img width="282" alt="G3" src="https://user-images.githubusercontent.com/45769317/86288582-ffdb2400-bb9e-11ea-83e9-8ed97fbe28a7.png">

Also counting in one gate per two bits of unpacking a scalar, we have 5 gates for every two bits.

<img width="571" alt="G4" src="https://user-images.githubusercontent.com/45769317/86288595-049fd800-bb9f-11ea-8539-95a685293a24.png">

EDIT: moved around two of the wire values and added the resulting wire equations in the original PLONK notation.

**Comment by vanishreerao** [comment]
<img width="502" alt="Screen Shot 2020-07-08 at 11 57 08 PM" src="https://user-images.githubusercontent.com/45769317/87007259-d01bb580-c176-11ea-81fc-53d49c0722d8.png">

**Comment by vanishreerao** [comment]
<img width="523" alt="Screen Shot 2020-07-08 at 11 58 40 PM" src="https://user-images.githubusercontent.com/45769317/87007350-fd686380-c176-11ea-989e-ac00f16ab9bf.png">
