### ISSUE TITLE
Document group_map public functions and structs

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#410]
It'd be nice to have documentation on the different functions and structs that have the keyword `pub`.

Also, some module-level documentation (using `//!` at the top of the file) with an example of how to use this library would be cool to have!

**Comment by aaronsens** [comment]
Going to work on this using these 3 references.
https://github.com/o1labs/snarky/blob/2e9013159ad0d1df0af681735b89518befc4be11/group_map/group_map.ml#L4
SvdW06: https://works.bepress.com/andrew_shallue/1/download/
WB19:https://eprint.iacr.org/2019/403

**Comment by mimoo** [comment]
fantastic, thanks :)
