### ISSUE TITLE
remove PhantomData from gates

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#411]
in https://github.com/o1-labs/proof-systems/blob/master/kimchi/src/circuits/polynomials/complete_add.rs#L50

```rust
#[derive(Default)]
pub struct CompleteAdd<F>(PhantomData<F>);
```

should be able to compile to

```rust
pub struct CompleteAdd<F>;
```

unless I'm missing something

(same for all the other gates)

**Comment by Trivo25** [comment]
will take a look ;)

**Comment by Trivo25** [comment]
Note: It won't compile as it is, the compiles requires (from my understanding) some type (like `PhantomData`) to pretend it actually stores a value, even though it doesn't. Removing it would probably require moving a few things around, not sure if that's what is wanted

**Comment by mimoo** [comment]
Ah interesting, maybe I was wrong in my assumption. I though it was here because we used to need to call `default()` on it. What was the error you got btw?

**Comment by Trivo25** [comment]
```
parameter `F` is never used
consider removing `F`, referring to it in a field, or using a marker such as `PhantomData`
if you intended `F` to be a const parameter, use `const F: usize` insteadrustc [E0392](https://doc.rust-lang.org/error-index.html#E0392)
```
I would suspect that removing `PhantomData` entirely would require some structural changes, but not sure - I could also just be missing something, tried a few things already

**Comment by mimoo** [comment]
Yeah I guess the error makes sense! You can't use a generic parameter if it's not used, hence PhantomData. Well thanks a lot for investigating this! Sorry for recommending a task with no better outcome :D

**Comment by Trivo25** [comment]
No worries, thats also a part of the process!
