### ISSUE TITLE
ConstraintSystem and ProverIndex

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#413]
The Prover index is split between a `ProverIndex` and a `ConstraintSystem` struct. The distinction between the two is quite arbitrary at the moment. Proposal:

- [ ] rename `ConstraintSystem` as `Circuit`
- [ ] move anything that doesn't help uniquely describing the circuit to `ProverIndex` (I believe only `public_input_size` and `gates` could remain in `Circuit`).
- [ ] implement `CryptoDigest` on this new `Circuit` type (and remove the previous `Circuit` type). See https://github.com/o1-labs/proof-systems/pull/859

**Comment by duguorong009** [comment]
@mimoo 
Will take this issue! :smile:

**Comment by duguorong009** [comment]
@mimoo 
I found that the `circuit` is already implemented [here](https://github.com/o1-labs/proof-systems/blob/master/kimchi/src/circuits/gate.rs#L404-L410).

Maybe, the issue was created long ago, and not reflecting the current codebase?
Please re-check the issue & repo.

**Comment by mimoo** [comment]
yeah, and that `Circuit` type can disappear after (because it's exactly what it is)
