### ISSUE TITLE
Design of custom constraints for poseidon

### ISSUE THREAD

**Issue by imeckler** [o1-labs/proof-systems#42]
https://hackmd.io/iTw9MuiITN-za__kp0LBow

**Comment by vanishreerao** [comment]
<img width="372" alt="Screen Shot 2020-06-04 at 8 28 48 PM" src="https://user-images.githubusercontent.com/45769317/83834107-60f80080-a6a2-11ea-82fa-feea98d315cf.png">

<img width="449" alt="Screen Shot 2020-06-04 at 8 29 11 PM" src="https://user-images.githubusercontent.com/45769317/83834115-65241e00-a6a2-11ea-84ef-dc690aee032d.png">



<img width="456" alt="Screen Shot 2020-06-04 at 8 30 58 PM" src="https://user-images.githubusercontent.com/45769317/83834121-681f0e80-a6a2-11ea-855f-57e954d38bd8.png">

**Comment by imeckler** [comment]
Let's define a turbo PLONK gate as being a degree 3 (I think it should be 3 or 4 if we want to change nothing else about the prover, I am not sure exactly...) element of

F[a, b, c, a', b', c']

Here a, b, c represent the 3 "columns" and a', b', c' the values of those columns in the "next" constraint.

Let's define a turbo PLONK constraint as simply being a list of gates. The point is that gates which are part of the same constraint can be squashed together using randomness as described here.

A turbo PLONK constraint system is a list of turbo PLONK constraints. We want to express this as a turbo PLONK constraint system.
