### ISSUE TITLE
Fr<G> and Fq<G>

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#426]
We use type aliases `Fr<G>` and `Fq<G>` in many places in the codebase. Every time we do this, we're re-declaring these.

A few things about that:

- [ ] `Fr` and `Fq` are not good names. Especially as Fq represents the base field of Vesta. Instead they should be named something like `ScalarField` and `BaseField`.
- [ ] We should avoid re-declaring these throughout the codebase. It would be good to declare these useful aliases within the utils crate, somewhere, as a prologue perhaps

if you don't know the prologue pattern, it's usually about defining something like this:

```rust
pub mod prologue {
  pub use super::{ScalarField, BaseField};
}
```

and then using it as 

```rust
use some_module::prologue::*;
```

- [ ] In some cases, it would be nice to be explicit about the use of Fr and Fq. For example, in `prover.rs`:

```diff
- let alpha_chal = ScalarChallenge(fq_sponge.challenge());
+ let alpha_chal: BaseField<F> = ScalarChallenge(fq_sponge.challenge());

//~ 18. Derive $\alpha$ from $\alpha'$ using the endomorphism (TODO: details)
- let alpha = alpha_chal.to_field(&index.srs.endo_r);
+ let alpha: ScalarField<F> = alpha_chal.to_field(&index.srs.endo_r);
```

**Comment by frisitano** [comment]
I will take this.

**Comment by frisitano** [comment]
What is the advantage of using the prologue pattern for this?  I'm guessing it's to do with future extensibility.  You can easily add to the prologue and the new types will be immediately available every the prologue is used?
