### ISSUE TITLE
Cannot open cryptography-rfcs repo?

### ISSUE THREAD

**Issue by 3for** [o1-labs/proof-systems#461]
Hi, in `hasher/README.md`, there's a reference to `https://github.com/o1-labs/cryptography-rfcs/blob/master/mina/001-poseidon-sponge.md`, but the page is not found. How can I see the detail info about 001-poseidon-sponge?

**Comment by mimoo** [comment]
cc @jspada , probably should be updated with the spec we have here https://o1-labs.github.io/proof-systems/specs/poseidon.html

**Comment by 3for** [comment]
@mimoo Thank you. It's helpful.
