### ISSUE TITLE
Enforce the public input length

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#466]
I don't think the public input length is enforced in any way on the verifier side. It'd be good to make sure that this is the case. (the length of the public input should probably be in the verifier index)

cc @querolita if we want to make this library usable for people with different usecases

**Comment by mrmr1993** [comment]
I don't think this is necessary. The verifier absorbs the public input into the sponge, so we'll notice pretty quickly if the prover sends a string of the wrong length.

**Comment by mimoo** [comment]
BTW @mrmr1993 this is the code on the verifier side:

```rust
    //~ 1. Commit to the negated public input polynomial.
    let lgr_comm = index
        .srs
        .lagrange_bases
        .get(&index.domain.size())
        .expect("pre-computed committed lagrange bases not found");
    let com: Vec<_> = lgr_comm
        .iter()
        .map(|c| PolyComm {
            unshifted: vec![*c],
            shifted: None,
        })
        .take(proof.public.len())
        .collect();
    let com_ref: Vec<_> = com.iter().collect();
    let elm: Vec<_> = proof.public.iter().map(|s| -*s).collect();
    let p_comm = PolyComm::<G>::multi_scalar_mul(&com_ref, &elm);
```

So I'm making a few proposals here:

* specify that better, it wasn't clear what happened on the spec side and had to go back to this
* add public_input_size to the verifier index, and check that the public input is of the correct size in verify
* remove the public input from the proof itself, make that an argument of verify

**Comment by mimoo** [comment]
reopening as we still haven't moved the public input to an argument of verify(). I'll change the title to reflect that.
