### ISSUE TITLE
restrict the use of `pub`

### ISSUE THREAD

**Issue by querolita** [o1-labs/proof-systems#469]
The current codebase is full of public functions that can be called from outside. We may want to study what functionalities are really meant to be public and which should not, to better envision the necessities of the public Kimchi API.

**Comment by mimoo** [comment]
I think it's not that bad to have `pub` modules and functions and structs, but `pub` fields in the structs are more problematic as sometimes they're not meant to be manually modified. I think when we notice these we could fix that.

**Comment by querolita** [comment]
Nice, I will share a list of the fields that could be potentially dangerous if they remain public.
