### ISSUE TITLE
Mina-book suggestions

### ISSUE THREAD

**Issue by 3for** [o1-labs/proof-systems#472]
Hi.
1) There are two sections about "commitments" with some overlapped contents:
* [https://o1-labs.github.io/proof-systems/fundamentals/zkbook_commitment.html](https://o1-labs.github.io/proof-systems/fundamentals/zkbook_commitment.html)
* [https://o1-labs.github.io/proof-systems/plonk/commitments.html](https://o1-labs.github.io/proof-systems/plonk/commitments.html)

2) And the image such as [`inner1.png`](https://o1-labs.github.io/proof-systems/plonk/inner_product.html) can not show in the page and some other pages.

**Comment by mimoo** [comment]
yeah we need to find a way to merge the two commitment pages. I'll try to find that image to fix, thanks for reporting.

**Comment by jspada** [comment]
These have been extended and merged.
