### ISSUE TITLE
book: bulletproof scheme

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#502]
from oamine on discord:

> mistake in the mina book related to the bulletproof scheme. The challenge x sent by the verifier should only be sent after the verfier receives the cross-product terms.

**Comment by duguorong009** [comment]
@mimoo @mrmr1993 
Can you please check the PR #883?
I just added a NOTE message for warning.

**Comment by mimoo** [comment]
thanks a lot for the fix :)
