### ISSUE TITLE
Move `runtime_tables`, `runtime_table_offset` out of `LookupConfiguration`

### ISSUE THREAD

**Issue by mrmr1993** [o1-labs/proof-systems#580]
`runtime_tables` and `runtime_table_offset` do not belong in [`LookupConfiguration`](https://github.com/o1-labs/proof-systems/blob/master/kimchi/src/circuits/lookup/constraints.rs#L340-L345), which is used to set up the general structure of the constraints without specifying the layout of the actual circuit. It would be best to move them to [`LookupConstraintSystem`](https://github.com/o1-labs/proof-systems/blob/master/kimchi/src/circuits/lookup/index.rs#L41), and store only a `max_runtime_table_width` in `LookupConfiguration`.

**Comment by mimoo** [comment]
it's actually not really clear to me why there's a separate `LookupConfiguration` type :o is it just a semantic distinction or is it important that there are values that must live in it instead of `LookupConstraintSystem`?

**Comment by mrmr1993** [comment]
It's important that they are distinct: one is the 'shape' of the constraint system from e.g. pickles' perspective, and the other contains the actual values, tables, etc. that are to be used.
