### ISSUE TITLE
Necessity of sponge parameters within the `ConstraintSystem` setup `create()` function

### ISSUE THREAD

**Issue by querolita** [o1-labs/proof-systems#591]
(Continuation of [this PR](https://github.com/o1-labs/proof-systems/pull/588))

As suggested by @mimoo in [Issue 541](https://github.com/o1-labs/proof-systems/issues/541), creating a constraint system used to be done like this:

```rust
let cs = ConstraintSystem::create(gates, fq_sponge_params, public, lookup_tables, runtime_tables);
```
Right now, this is simplified by having the ability to configure **most** of these parameters individually and incrementally like this:

```rust
let cs = ConstraintSystem::create(gates, fq_sponge_params).public(p).lookup(lt).runtime(rt).precomputations(pc).build();
```
The issue is:
When are we really using the sponge parameters? Are they always necessary to be included in the very first `create()` method together with the gates? Should they have an additional setter, which is optional as the rest like `public()` or `runtime()`? Are there any parts of the code where the sponge parameters should be an `Option` type?

**Comment by fabrizio-m** [comment]
I'll take it.

**Comment by fabrizio-m** [comment]
Those parameters are necessary for: 
- The Poseidon gate.
- To generate the `u` and `v` challenges.

For the first item the optionality of the parameters depends on the optionality of the Poseidon gate.
More importantly, for the second item the challenges are used to create the opening proofs, I will look at SRS::open() a bit more but it seems that those challenges can't be optional.

**Comment by mimoo** [comment]
Actually IIUC the poseidon gate doesn't use this param, it uses the `fr_sponge_params` in the `ConstraintSystem` instead. But yeah the sponge we use for Fiat-Shamir does use `fq_sponge_params`. I'm wondering if it would make sense to move this to the SRS?

**Comment by fabrizio-m** [comment]
There seems to be some inconsistencies with the names, but this `fq_sponge_params` seems to be the `fr_sponge_params` that is used in poseidon.
the builder created for the benchmark takes `fp_sponge_params` from `oracle::pasta::fp_kimchi::params()`, then Builder::build() stores it in `ConstraintSystem`, field `fr_sponge_params`.
By the way, is there any meaning to fp, fr and fp beyond differentiating fields?

About moving the params to the SRS, I think it depends on how normal it will to change the params.
Are there any reason to use more than one sponge for the same curve?

**Comment by mimoo** [comment]
> By the way, is there any meaning to fp, fr and fp beyond differentiating fields?

from https://o1-labs.github.io/proof-systems/specs/pasta.html

<img width="780" alt="Screen Shot 2022-06-06 at 6 25 16 PM" src="https://user-images.githubusercontent.com/1316043/172203158-a1783741-6116-4d9a-b116-52cc49d54cc9.png">

We've changed Fr/Fq to ScalarField/BaseField where we could, but there might still be some remaining instances that we need to change (thinking about that, we also have endo_q and endo_r that we should change to endo_basefield and endo_scalarfield or something like that)

> Are there any reason to use more than one sponge for the same curve?

I don't think so, and as far as I know we just use these two parameters all the time. So might as well move this to the SRS https://o1-labs.github.io/proof-systems/specs/urs.html

**Comment by fabrizio-m** [comment]
Makes sense, I will look at which changes would be required to move the sponge params to the SRS.

**Comment by fabrizio-m** [comment]
The only problem seems to be that now `CircuitGate::verify_poseidon()` can't access`fp_sponge_params.mds` from the `ConstraintSystem`
I can see two ways to solve that:
- Make `ConstraintSystem::verify()` take an SRS, but that may require changing the generic of `ConstraintSystem`.
- Make `ConstraintSystem::verify()` private and to take the sponge params, and create an analogous method in `ProverIndex` that will call the old `verify()` passing it the sponge params.

**Comment by joseandro** [comment]
@querolita could you set an estimate to this task?

**Comment by querolita** [comment]
Estimated. It has a PR now, so it is a matter of hours that it gets closed.

**Comment by fabrizio-m** [comment]
Closing in favor of #639 that will make sponge params part of the curve and thus no longer necessary to be provided.
