### ISSUE TITLE
snarky-rs: optimize zero gates

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#598]
don't use a zero gate at the end of gadgets like Poseidon (and others). instead use a double generic gate that doesn't use the first three register (the first generic gate), so that we can still make use of the second generic gate within it.

**Comment by mrmr1993** [comment]
Would be nice to do this on the Mina side too (in `plonk_constraint_system.ml`). Should be easy to add there, but will require some OCaml know-how.

**Comment by mimoo** [comment]
We can't do it in a few lines of code for the endo gate because it doesn't place the result in the first three columns. We have to change the layout to move these to the first three columns (which shouldn't be too hard, but is a breaking change)

**Comment by mimoo** [comment]
not super nice to implement it for poseidon as well: https://github.com/o1-labs/proof-systems/pull/632 because if it queues the gate then it will mess up the permutation that links the last zero/generic gate to the previous row. So it only works in the case there's already a queued generic gate. Not sure if worth it
