### ISSUE TITLE
range check gate - use the new circuit API for testing

### ISSUE THREAD

**Issue by jspada** [o1-labs/proof-systems#638]
This probably consists of two things
1) Add range check to the new circuit API
2) Switch tests to use new circuit API

Would be good to simplify the range check tests also.

**Comment by mimoo** [comment]
https://hackmd.io/i9aW1BlrSsmUJO8c9Vz3DQ <-- btw the write up on how to do this

**Comment by jspada** [comment]
It seems like the new circuit API is still in a state of flux, so I can't do this task yet.
