### ISSUE TITLE
verify: move public input from proof to argument of the verify function

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#644]
It doesn't make sense to have the public input be part of the proof

cc @rot256

**Comment by imikushin** [comment]
Thinking of picking this up.

**Comment by imikushin** [comment]
So, #976 implements this. What do folks think about adding `verifier_index` as an argument to `batch_verify()`? It makes the API a little cleaner, in my opinion. 

But, since I'm new here, I may be missing use cases when there is a verifier index per proof (which may be missing tests then).
