### ISSUE TITLE
Should we move T: Field to T: PrimeField everywhere?

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#688]
Since kimchi is built exclusively for prime fields (and not for extension fields, for example), it might make sense to move to `PrimeField` everywhere instead of having `Field`, `FftField`, and `PrimeField` all over the place

**Comment by mimoo** [comment]
there's also `SquareRootField` used in some places

**Comment by mimoo** [comment]
as a helper:

```rust
SquareRootField: Field
PrimeField: Field + FftField
```

**Comment by fabrizio-m** [comment]
I think the only disadvantage is that some bounds will apply unnecessary constraints and it will be a bit harder to know if something needs `PrimeField` or only a subset of it. 
But I don't if that's even something that's true now, if it isn't I think is more consistent to just use `PrimeField`.
