### ISSUE TITLE
rename `Affine` to `Pallas/Vesta` in mina-curves

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#692]
<img width="842" alt="Screen Shot 2022-07-14 at 12 01 26 PM" src="https://user-images.githubusercontent.com/1316043/179062516-2b3b9ddc-94f8-4117-b144-7f13a03fa6db.png">

**Comment by fabrizio-m** [comment]
The `Projective` type seems to be less used so I think they could become `[Curve]Projective` for consistency while the `Affine` gets the shorter just `[Curve]`.
