### ISSUE TITLE
issue with running cargo build in the project

### ISSUE THREAD

**Issue by vivanraaj** [o1-labs/proof-systems#694]
I am getting the error of "error: the 'rustc' binary, normally provided by the 'rustc' component, is not applicable to the '1.58.0-x86_64-unknown-linux-gnu' toolchain"
after running "cargo run".

is there a proper version name for the rust version in the rust-toolchain.toml file?

**Comment by mimoo** [comment]
can you try to do `rustup update`, and what does `rustup show` says?

**Comment by vivanraaj** [comment]
solved the issue. i needed to reinstall rustc due to conflicting packages. its working now
