### ISSUE TITLE
remove array_init dependency

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#716]
Looks like [array::from_fn](https://doc.rust-lang.org/stable/std/array/fn.from_fn.html) got stabilized in the latest Rust, so we don't need array_init anymore

**Comment by duguorong009** [comment]
Can I take this one? @mimoo 
In fact, I already done replacement in my local machine.
But, I am not sure if it is okay to create PR without any inform.
(maybe, just following contribute guideline is enough?)

**Comment by duguorong009** [comment]
@mimoo 
Created a first contribution PR. 
Please check & give me the review.

**Comment by mimoo** [comment]
hey! Sorry for the late response, but I see that you already did it so thanks a lot : )

**Comment by mimoo** [comment]
reopening as it looks like array-init is still part of the `Cargo.toml`

**Comment by duguorong009** [comment]
@mimoo 
I also noticed that `array-init` still exists in some `Cargo.toml` files.
Will re-create the PR to fix it.

**Comment by duguorong009** [comment]
Created a new PR #748
