### ISSUE TITLE
Witness generator (public outputs) from proving key

### ISSUE THREAD

**Issue by frisitano** [o1-labs/proof-systems#824]
It would be of value to provide a feature where a user can create a witness generator from a mina proving key.  The witness generator should take public and private inputs as arguments and then generate the execution trace from which the user can extract public outputs.

**Comment by mimoo** [comment]
I think once we have snarky-rs (implementation of snarky in Rust, that we've been working on in https://github.com/o1-labs/proof-systems/tree/mimoo/snarky2), and we merge the backend and the wrapper (in snarky-rs), then we'll be able to just serialize the symbolic execution trace and the variables, and have a simple interpreter in any language build the execution trace. cc @fabrizio-m

**Comment by frisitano** [comment]
Any update on this? @mimoo
