### ISSUE TITLE
missing of the value "b" in the polynomial commitment verification algorithm

### ISSUE THREAD

**Issue by hjlpb** [o1-labs/proof-systems#829]
In the file "proof-systems/book/src/fundamentals/zkbook_commitment.md", the section of "Constructing polynomial commitment schemes",  as in the following picture, it seems the value "b" is missed during verification?
![commitment](https://user-images.githubusercontent.com/20498177/199659314-f0ba061d-d8fb-48d0-a7fe-14a8f3ff219b.jpg)

**Comment by duguorong009** [comment]
@mimoo 
Can you make time to check the PR #861 ?
Thanks in advance.

**Comment by mimoo** [comment]
thank you both!
