### ISSUE TITLE
absorb_evaluations should deconstruct the input

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#841]
the current code is prone to error as we can forget to absorb things:

```rust
    fn absorb_evaluations<const N: usize>(&mut self, e: [&ProofEvaluations<Vec<Fr>>; N]) {
        self.last_squeezed = vec![];
        let e = ProofEvaluations::transpose(e);
        let mut points = vec![
            &e.z,
            &e.generic_selector,
            &e.poseidon_selector,
            &e.w[0],
```

we should modify that to something like this:

```rust
    fn absorb_evaluations<const N: usize>(&mut self, e: [&ProofEvaluations<Vec<Fr>>; N]) {
        self.last_squeezed = vec![];
        let &ProofEvaluations<_> { z, generic_selector, poseidon_selector, w,  } = &ProofEvaluations::transpose(e);
        let mut points = vec![
            &z,
            &generic_selector,
            &poseidon_selector,
            &w[0],
```

I think ideally we would have something [like this](https://github.com/o1-labs/proof-systems/blob/501616da46b26d71114f92dc4524dbf27ee97a2d/kimchi/src/proof.rs#L200) from https://github.com/o1-labs/proof-systems/pull/680/files

**Comment by duguorong009** [comment]
@mimoo 
Can you check the following PR?(I would like to take the issue)
https://github.com/duguorong009/proof-systems/pull/2
I think the simple deconstruction you showed in references is just enough, no need to add other stuff like `iter`

**Comment by duguorong009** [comment]
@mimoo 
Please check the PR I created for this issue.
#875

**Comment by mrmr1993** [comment]
Done in https://github.com/o1-labs/proof-systems/pull/875 (thanks @duguorong009!). Closing.
