### ISSUE TITLE
[CI] integrate clippy-beta?

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#855]
zcash uses this nice thing where you can see clippy warnings within the PR's code

https://github.com/zcash/pasta_curves/blob/main/.github/workflows/ci.yml#L106

<img width="1272" alt="Screen Shot 2022-11-21 at 1 30 14 PM" src="https://user-images.githubusercontent.com/1316043/203161942-80e496bb-4ced-4934-8a54-0b67ca5925c3.png">

**Comment by duguorong009** [comment]
@mimoo 
I would like to take this one.
I think you can check the test PR https://github.com/duguorong009/proof-systems/pull/3

I think this CI integration have one intrinsic [limitation](https://github.com/actions-rs/clippy-check#limitations)
This means that the `clippy-check` action would NOT work with contribution PRs.
Any idea? @mimoo

**Comment by duguorong009** [comment]
@mimoo 
Please review the PR I created
https://github.com/o1-labs/proof-systems/pull/874

**Comment by mrmr1993** [comment]
Closing, https://github.com/o1-labs/proof-systems/pull/874 has landed.
