### ISSUE TITLE
Pad chunked commitments to always have the same length

### ISSUE THREAD

**Issue by mrmr1993** [o1-labs/proof-systems#888]
Currently, we only generate commitments for polynomials up to the maximum chunk where we have non-zero coefficients. This leaks information about the underlying polynomials.

Instead, we should pad with 'zero' commitments. After blinding, the verifier won't be able to infer anything about underlying polynomial.

Concretely, we should add a `polynomial_degree` argument to the [`commit_non_hiding`](https://github.com/o1-labs/proof-systems/blob/e6c72860e9c00987bd490a3f545406a4bece9d68/poly-commitment/src/commitment.rs#L538) function, and use that for padding.

**Comment by duguorong009** [comment]
@mrmr1993 
I would like to take this issue!

One question.
Is there any need to add a `polynomial_degree` argument to the function?
The `commit_non_hiding` function already gets the argument of `plnm`(type is `DensePolynomial`).
Then, I can get the `polynomial_degree` easily, just by `plnm.degree()`.
I cannot see why I need extra argument for this issue solution.

**Comment by duguorong009** [comment]
@mrmr1993 
Can you review the PR #891 I created for the issue?
Thanks!

**Comment by mrmr1993** [comment]
> Is there any need to add a `polynomial_degree` argument to the function?

Sadly, yes. Any leading zero coefficients in the polynomial will not count towards the polynomial degree, but we really do want to generate chunked commitments for all of the chunks, even if they're filled with zeros.

Sorry for not replying to this before you started on the PR; thanks for being so fast with it!

**Comment by mrmr1993** [comment]
By my reading, it's explicitly reducing the degree from the 'desired' degree (which might have leading zero coefficients) to the 'actual' degree. See e.g. [here](https://github.com/arkworks-rs/algebra/blob/e062140351e7775d30c8b0167fbef048fcd4535e/poly/src/polynomial/univariate/dense.rs#L107). Looks like it's still worthwhile passing the desired degree as an argument, since the contents of the polynomial can otherwise affect the number of chunks.

**Comment by duguorong009** [comment]
@mrmr1993 
I still think I can get the polynomial degree by `DensePolynomial::degree()`.
The definition of `DensePolynomial` is like: https://github.com/arkworks-rs/algebra/blob/master/poly/src/polynomial/univariate/dense.rs#L23
From the definition, we can get that the last element of `Vec<F>` is the degree of polynomial.
If any leading zeros, it means those zeros are not for the degree.
For example: 
```
[0, 1, 4, 0, 0, -2] -> degree 5
[0, 1, 4, 0, 0, -2, 0, 0] -> degree 5 (will truncate the last zeros)
[0, 1, 4, 0, 0, 0, 0, -1] -> degree 7
```

**Comment by mimoo** [comment]
I think a prerequesite to this PR would be to figure out the degree of all the polynomials that we're committing to in the protocol (both on the prover and verifier side). This is related to https://github.com/o1-labs/proof-systems/issues/147

**Comment by duguorong009** [comment]
> Looks like it's still worthwhile passing the desired degree as an argument, since the contents of the polynomial can otherwise affect the number of chunks.

Thanks for the details! @mimoo @mrmr1993 
While I re-reading all the comments you left, I found that above comment is most important for my understanding.
I think the intention of @mrmr1993 is to add the **desired** degree of polynomial to be committed, not the real degree of polynomial to be committed.

Thanks again! 
Will try to fix the PR & ask more review/comments. :slightly_smiling_face:

**Comment by duguorong009** [comment]
@mimoo 
Can you give me explanation of this [comment](https://github.com/o1-labs/proof-systems/issues/147#issuecomment-1072668191)?
You mentioned that this code gives us the expected number of commitments.
I think we should embed this code or the output of code into this PR.

**Comment by mimoo** [comment]
maybe a good approach is to do something like that:

```rust
impl ProverProof {
  fn validate(&self) -> Result<()> {
     let &ProverProof { commitments, .. } = self;
     commitments.validate()?;
  }
}

impl ProverCommitments {
   fn validate(&self) -> Result<()> {
    let &ProverCommitments { w_comm, z_comm, t_comm, .. } = self;
    w_comm.find(|com| com.len() != 1).do_something()?;
    if z_comm.len() != 1 { return some error };
    if t_comm.len() != 7 { return some error };
  }
}
