### ISSUE TITLE
glv decomposition helper

### ISSUE THREAD

**Issue by fabrizio-m** [o1-labs/proof-systems#959]
we can make some function to glv decompose a scalar, so that all scalar multiplications on circuit will be able to easily use the endo scalar multiplication gate.

**Comment by mimoo** [comment]
can we get rid of the scalar mul gate if we do this?

**Comment by fabrizio-m** [comment]
If there are no retro compatibility issues I suppose yes, if both scalar multiplications work with any scalar, we should only need one, I don't know if the normal scalar provides any unique functionality.
