### ISSUE TITLE
Break the kimchi specification in separate sections in the boook

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#996]
Small changes have had a tendency to break the whole [kimchi specification](https://o1-labs.github.io/proof-systems/specs/kimchi.html). I'm not sure if we have a good way to prevent that automatically. I couldn't find good linters for markdown + LaTeX. In the absence of that I think there are two main strategies:

* make sure that specifications are not broken as part of reviewing PRs
* break out the spec sections so that a breakage somewhere doesn't break the whole specification

This issue is about the latter. The obvious target IMO are the [custom gates](https://o1-labs.github.io/proof-systems/specs/kimchi.html#gates):

* it would make sense to have them be in their own sections
* they tend to be the parts that break the spec the most
* there is some annoying deeply nested header action going on there that would benefit from being a top-level section

**Comment by querolita** [comment]
> make sure that specifications are not broken as part of reviewing PRs
This seems tricky, since they compile locally and then fail in master 😢

**Comment by querolita** [comment]
I agree with moving the custom gates to their own sections

**Comment by mimoo** [comment]
> since they compile locally and then fail in master

to me it sounds like a bug that's orthogonal to the issue here : o

**Comment by mimoo** [comment]
fixed that issue here: https://github.com/o1-labs/proof-systems/pull/1005
